<?php 
/*
 * Api2PostnordComLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class AreaOfNotificationDto implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var array|null $postalCodes public property
     */
    public $postalCodes;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array|null        $postalCodes   Initialization value for the property $this->postalCodes
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->postalCodes = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['postalCodes'] = $this->postalCodes;

        return $json;
    }
}