<?php 
/*
 * Api2PostnordComLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CoordinateDto implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var string $countryCode public property
     */
    public $countryCode;

    /**
     * @todo Write general description for this property
     * @required
     * @var double $easting public property
     */
    public $easting;

    /**
     * @todo Write general description for this property
     * @required
     * @var double $northing public property
     */
    public $northing;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $srId public property
     */
    public $srId;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $countryCode   Initialization value for the property $this->countryCode
     * @param   double            $easting       Initialization value for the property $this->easting    
     * @param   double            $northing      Initialization value for the property $this->northing   
     * @param   string            $srId          Initialization value for the property $this->srId       
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->countryCode = func_get_arg(0);
            $this->easting     = func_get_arg(1);
            $this->northing    = func_get_arg(2);
            $this->srId        = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['countryCode'] = $this->countryCode;
        $json['easting']     = $this->easting;
        $json['northing']    = $this->northing;
        $json['srId']        = $this->srId;

        return $json;
    }
}