<?php 
/*
 * Api2PostnordComLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class DropOffTimeDto implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var DropOffTimeDataDto|null[] $dropOffTimeData public property
     */
    public $dropOffTimeData;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $serviceId public property
     */
    public $serviceId;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array|null        $dropOffTimeData   Initialization value for the property $this->dropOffTimeData
     * @param   string            $serviceId         Initialization value for the property $this->serviceId      
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->dropOffTimeData = func_get_arg(0);
            $this->serviceId       = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['dropOffTimeData'] = $this->dropOffTimeData;
        $json['serviceId']       = $this->serviceId;

        return $json;
    }
}