<?php 
/*
 * Api2PostnordComLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ServicePointInformationDto implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var CoordinateDto|null[] $coordinate public property
     */
    public $coordinate;

    /**
     * @todo Write general description for this property
     * @required
     * @var AddressDto $deliveryAddress public property
     */
    public $deliveryAddress;

    /**
     * @todo Write general description for this property
     * @var DropOffTimeDto|null $dropOffTime public property
     */
    public $dropOffTime;

    /**
     * @todo Write general description for this property
     * @var bool|null $eligibleParcelOutlet public property
     */
    public $eligibleParcelOutlet;

    /**
     * @todo Write general description for this property
     * @var string|null $handlingOffice public property
     */
    public $handlingOffice;

    /**
     * @todo Write general description for this property
     * @var string|null $locationDetail public property
     */
    public $locationDetail;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @var AreaOfNotificationDto|null $notificationArea public property
     */
    public $notificationArea;

    /**
     * @todo Write general description for this property
     * @var OpeningHourDto|null[] $openingHour public property
     */
    public $openingHour;

    /**
     * @todo Write general description for this property
     * @var string|null $routingCode public property
     */
    public $routingCode;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $servicePointId public property
     */
    public $servicePointId;

    /**
     * @todo Write general description for this property
     * @required
     * @var AddressDto $visitingAddress public property
     */
    public $visitingAddress;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array|null        $coordinate             Initialization value for the property $this->coordinate          
     * @param   AddressDto        $deliveryAddress        Initialization value for the property $this->deliveryAddress     
     * @param   DropOffTimeDto|null   $dropOffTime            Initialization value for the property $this->dropOffTime         
     * @param   bool|null         $eligibleParcelOutlet   Initialization value for the property $this->eligibleParcelOutlet
     * @param   string|null       $handlingOffice         Initialization value for the property $this->handlingOffice      
     * @param   string|null       $locationDetail         Initialization value for the property $this->locationDetail      
     * @param   string            $name                   Initialization value for the property $this->name                
     * @param   AreaOfNotificationDto|null   $notificationArea       Initialization value for the property $this->notificationArea    
     * @param   array|null        $openingHour            Initialization value for the property $this->openingHour         
     * @param   string|null       $routingCode            Initialization value for the property $this->routingCode         
     * @param   string            $servicePointId         Initialization value for the property $this->servicePointId      
     * @param   AddressDto        $visitingAddress        Initialization value for the property $this->visitingAddress     
     */
    public function __construct()
    {
        if(12 == func_num_args())
        {
            $this->coordinate           = func_get_arg(0);
            $this->deliveryAddress      = func_get_arg(1);
            $this->dropOffTime          = func_get_arg(2);
            $this->eligibleParcelOutlet = func_get_arg(3);
            $this->handlingOffice       = func_get_arg(4);
            $this->locationDetail       = func_get_arg(5);
            $this->name                 = func_get_arg(6);
            $this->notificationArea     = func_get_arg(7);
            $this->openingHour          = func_get_arg(8);
            $this->routingCode          = func_get_arg(9);
            $this->servicePointId       = func_get_arg(10);
            $this->visitingAddress      = func_get_arg(11);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['coordinate']           = $this->coordinate;
        $json['deliveryAddress']      = $this->deliveryAddress;
        $json['dropOffTime']          = $this->dropOffTime;
        $json['eligibleParcelOutlet'] = $this->eligibleParcelOutlet;
        $json['handlingOffice']       = $this->handlingOffice;
        $json['locationDetail']       = $this->locationDetail;
        $json['name']                 = $this->name;
        $json['notificationArea']     = $this->notificationArea;
        $json['openingHour']          = $this->openingHour;
        $json['routingCode']          = $this->routingCode;
        $json['servicePointId']       = $this->servicePointId;
        $json['visitingAddress']      = $this->visitingAddress;

        return $json;
    }
}