<?php 
/*
 * Api2PostnordComLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ServicePointInformationResponse implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var CompositeFault|null $compositeFault public property
     */
    public $compositeFault;

    /**
     * @todo Write general description for this property
     * @var CustomerSupportDto|null[] $customerSupport public property
     */
    public $customerSupport;

    /**
     * @todo Write general description for this property
     * @var ServicePointInformationDto|null[] $servicePoints public property
     */
    public $servicePoints;

    /**
     * Constructor to set initial or default values of member properties
     * @param   CompositeFault|null   $compositeFault    Initialization value for the property $this->compositeFault 
     * @param   array|null        $customerSupport   Initialization value for the property $this->customerSupport
     * @param   array|null        $servicePoints     Initialization value for the property $this->servicePoints  
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->compositeFault  = func_get_arg(0);
            $this->customerSupport = func_get_arg(1);
            $this->servicePoints   = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['compositeFault']  = $this->compositeFault;
        $json['customerSupport'] = $this->customerSupport;
        $json['servicePoints']   = $this->servicePoints;

        return $json;
    }
}