<?php
/*
 * Api2PostnordComLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComLib;

use Api2PostnordComLib\Controllers;

/**
 * Api2PostnordComLib client class
 */
class Api2PostnordComClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct($apikey = NULL)
    {
        Configuration::$apikey = $apikey ? $apikey : Configuration::$apikey;
    }
 
    /**
     * Singleton access to API controller
     * @return Controllers\APIController The *Singleton* instance
     */
    public function getAPI()
    {
        return Controllers\APIController::getInstance();
    }
}